# Generated by Django 3.0.4 on 2020-03-28 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=100, unique=True)),
                ('link_titlu', models.SlugField(max_length=100, unique=True)),
                ('continut', models.TextField()),
                ('creat', models.DateTimeField(auto_now_add=True)),
                ('actualizat', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postari', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
